version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - NODE_ENV=development

  frontend:
    build: ./Frontend
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend:/usr/src/app
    environment:
      - NODE_ENV=development
